// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqcSD-VxJzHlYPxheSTcuY4YxO2HWlR6o',
    appId: '1:427198525393:web:5c1290c499c00ace61baf0',
    messagingSenderId: '427198525393',
    projectId: 'pizza-app-fa0c9',
    authDomain: 'pizza-app-fa0c9.firebaseapp.com',
    storageBucket: 'pizza-app-fa0c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOVTAZGKiYv_tPMGJIx8ybQaw_N4KzM9k',
    appId: '1:427198525393:android:9da99ee56d1cbda261baf0',
    messagingSenderId: '427198525393',
    projectId: 'pizza-app-fa0c9',
    storageBucket: 'pizza-app-fa0c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJaoCg8hWzWPVUGwW9WNupOEHkg2NLbd0',
    appId: '1:427198525393:ios:f5e3b1a6b54427aa61baf0',
    messagingSenderId: '427198525393',
    projectId: 'pizza-app-fa0c9',
    storageBucket: 'pizza-app-fa0c9.appspot.com',
    iosBundleId: 'com.example.pizzaAppBlocFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJaoCg8hWzWPVUGwW9WNupOEHkg2NLbd0',
    appId: '1:427198525393:ios:5b43f25eca6a228b61baf0',
    messagingSenderId: '427198525393',
    projectId: 'pizza-app-fa0c9',
    storageBucket: 'pizza-app-fa0c9.appspot.com',
    iosBundleId: 'com.example.pizzaAppBlocFirebase.RunnerTests',
  );
}
